language: go

go:
  - "1.14"
  - master

before_install:
  - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

services:
  - mysql
  - mongodb

before_install:
  - mysql -e 'CREATE DATABASE test;'
